version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  app:
    container_name: vulhubManagement
    environment:
      - FLASK_APP=/app/src/web/main
      - FLASK_ENV=development
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
      - ./vulnerability/:/app/vulnerability
