version: '3'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    container_name: vulhubManagement
    environment:
      - FLASK_APP=/app/src/web/main
      - FLASK_ENV=development
    build:
      dockerfile: ./Dockerfile-web
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
      - ./vulnerability/:/app/vulnerability
  composer:
    container_name: vulhubComposer
    privileged: true
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./src:/app/src
      - ./vulnerability/:/app/vulnerability
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      dockerfile: ./Dockerfile-composer
