FROM python:3.9.2-alpine

WORKDIR /app
RUN apk upgrade --no-cache && apk add docker docker-compose --no-cache
COPY ./src/requirements.txt .
RUN pip install -r requirements.txt
CMD ["rq", "worker", "-c", "src.config"]
